name: Daily Github Review Stats of Scheduling Team

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  review-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.2"
      - run: |
          make run-debug
        env:
          GHSTATS_GITHUB_TOKEN: ${{ secrets.GHSTATS_GITHUB_TOKEN_1 }}
          GHSTATS_FEISHU_WEBHOOK_TOKEN: ${{ secrets.GHSTATS_FEISHU_WEBHOOK_TOKEN }}
